export const JOIN_ROOM = 'JOIN_ROOM';
export const CREATE_ROOM = 'CREATE_ROOM';
export const GET_AUTH_STATUS = 'GET_AUTH_STATUS';
export const GET_USERS_CONNECTION_COUNT = 'GET_USERS_CONNECTION_COUNT';
export const UPDATE_STATE = 'UPDATE_STATE';
